INSERT INTO products (sku_name, name, hsn_code, price_per_unit, category) VALUES
('Akita', 'AKI', NULL, 675, 'fabric'),
('Akron', 'AKR', NULL, 650, 'fabric'),
('Alexis White', 'ALE', NULL, 966, 'fabric'),
('Amelia', 'AME', NULL, 760, 'fabric'),
('Ankara Plus White', 'ANK', NULL, 699, 'fabric'),
('Aurelia', 'AUR', NULL, 785, 'fabric'),
('Belfast', 'BEL', NULL, 645, 'fabric'),
('Belgred Tencel', 'TENC', NULL, 685, 'fabric'),
('Bergen/ Essence', 'BERG', NULL, 525, 'fabric'),
('BESAL', 'BESA', NULL, 640, 'fabric'),
('BIENNE', 'BIEN', NULL, 640, 'fabric'),
('Breda Tencel White', 'TENC', NULL, 675, 'fabric'),
('Cairns Tencel Mel', 'TENC', NULL, 815, 'fabric'),
('Catania Tencel', 'TENC', NULL, 735, 'fabric'),
('Chiba', 'CHI', NULL, 960, 'fabric'),
('Clara', 'CLA', NULL, 566, 'fabric'),
('Costa Rica', 'COST', NULL, 565, 'fabric'),
('Doha', 'DOHA', NULL, 953, 'fabric'),
('Elastin', 'ELAS', NULL, 653, 'fabric'),
('Elsa', 'ELSA', NULL, 784, 'fabric'),
('fern', 'FER', NULL, 474, 'fabric'),
('Fili', 'FILI', NULL, 521, 'fabric'),
('Freshno Perfume', 'FRES', NULL, 666, 'fabric'),
('Gravitas', 'GRAV', NULL, 1608, 'fabric'),
('Imperial', 'IMP', NULL, 656, 'fabric'),
('Jamaica FC', 'JAMI', NULL, 1035, 'fabric'),
('Jamber', 'JEM', NULL, 955, 'fabric'),
('Jasper', 'JAS', NULL, 955, 'fabric'),
('JAZZLYN', 'JAZ', NULL, 955, 'fabric'),
('Jena', 'JEN', NULL, 1125, 'fabric'),
('Jersey', 'JERS', NULL, 955, 'fabric'),
('Joplin', 'JOP', NULL, 1125, 'fabric'),
('Kenosha', 'KP', NULL, 599, 'fabric'),
('Kimberley', 'KIM', NULL, 654, 'fabric'),
('KOVEL', 'KOV', NULL, 688, 'fabric'),
('Kupa', 'KUP', NULL, 679, 'fabric'),
('Kupa Plus', 'KUP +', NULL, 730, 'fabric'),
('Largo', 'L', NULL, 755, 'fabric'),
('Largo plus', 'LP', NULL, 755, 'fabric'),
('Larida', 'LAR', NULL, 775, 'fabric'),
('Larida Plus', 'LAR +', NULL, 775, 'fabric'),
('Lawton FC', 'LAW FC', NULL, 925, 'fabric'),
('Leon', 'LEO', NULL, 539, 'fabric'),
('Leon Stiff', 'LEO STIF', NULL, 539, 'fabric'),
('LESBEN Tencel', 'TENC', NULL, 839, 'fabric'),
('Lincolin FC', 'LIN FC', NULL, 892, 'fabric'),
('Lucena Tencel PD', 'TENC PD', NULL, 796, 'fabric'),
('Lugano Tencel', 'TENC', NULL, 846, 'fabric'),
('Maldova Tencel', 'TENC', NULL, 788, 'fabric'),
('Manison White', 'MANSI', NULL, 553, 'fabric'),
('Messi White', 'MESS', NULL, 1163, 'fabric'),
('Minoplus', 'MINO', NULL, 1031, 'fabric'),
('Monklova White', 'MONK', NULL, 575, 'fabric'),
('Napa(24 Shaft)', 'NAPA', NULL, 844, 'fabric'),
('NARITA', 'NART', NULL, 835, 'fabric'),
('Nelson', 'NELS', NULL, 740, 'fabric'),
('Nice', 'N', NULL, 799, 'fabric'),
('Nicosia DB FC', 'NISC DB', NULL, 894, 'fabric'),
('Nimes DB FC', 'MNIM FC', NULL, 1015, 'fabric'),
('Nobel', 'NOB', NULL, 1558, 'fabric'),
('Novara DB FC 2 (24 Shaft)', 'NOVRA', NULL, 1015, 'fabric'),
('Novi', 'NOVI', NULL, 810, 'fabric'),
('OSAKA TWILL', 'OSK', NULL, 782, 'fabric'),
('Oxburg', 'OXBU', NULL, 778, 'fabric'),
('PALLAZO White', 'PALZ', NULL, 505, 'fabric'),
('Prato Plus', 'PRA', NULL, 1057, 'fabric'),
('Reno', 'REN', NULL, 762, 'fabric'),
('Renosha', 'RENOS', NULL, 1028, 'fabric'),
('Rialto', 'RIAL', NULL, 958, 'fabric'),
('Riverside', 'RIVER', NULL, 786, 'fabric'),
('Salzburg', 'SALZ', NULL, 1350, 'fabric'),
('Sisli SS', 'SISL', NULL, 857, 'fabric'),
('Skylar', 'SKY', NULL, 630, 'fabric'),
('Sochi', 'SOC', NULL, 852, 'fabric'),
('Sofia', 'SOF', NULL, 640, 'fabric'),
('Splendora', 'SPLE', NULL, 817, 'fabric'),
('Suwon Tencel PD', 'SUWO', NULL, 692, 'fabric'),
('Takeo', 'TAKE', NULL, 828, 'fabric'),
('TANZA', 'TANZ', NULL, 1380, 'fabric'),
('Texco', 'TEX', NULL, 1127, 'fabric'),
('Trinity', 'TRI', NULL, 875, 'fabric'),
('Tudor', 'TUD', NULL, 835, 'fabric'),
('Urbino', 'URB', NULL, 756, 'fabric'),
('Valencia', 'VALE', NULL, 799, 'fabric'),
('Velino', 'VELI', NULL, 778, 'fabric'),
('Veracruz', 'VERE', NULL, 719, 'fabric'),
('Veracruz plus White', 'VERE +', NULL, 719, 'fabric'),
('Verona', 'VERO', NULL, 450, 'fabric'),
('Victoria', 'VIC', NULL, 828, 'fabric'),
('Weston', 'WES', NULL, 685, 'fabric'),
('WILLA FC', 'WIL', NULL, 822, 'fabric');
