ALTER TABLE staff
ADD COLUMN IF NOT EXISTS can_view_orders BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS can_view_inventory BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS can_view_agents BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS can_view_staff BOOLEAN DEFAULT false;
